blank_issues_enabled: false
contact_links:
  - name: Report Other Issue
    url: https://github.com/make-models-fair/make-models-fair.github.io/issues
    about: Use the main repository to report issues related or unrelated to coordination
